'use strict';
const examParams=new URLSearchParams(location.search),sebPractice=examParams.get('seb')==='1',sebExamId=examParams.get('exam');
document.body.classList.toggle('seb-session',sebPractice);
const originalWorkspace=workspace,originalStart=requestStart,originalRenderAnswers=renderAnswers,originalResultDetail=resultDetail,originalFinish=finishAttempt,originalRenderRoute=renderRoute;
function answeredPdfOptions(attempt,paper,readOnly=false){return{attempt,paper,readOnly,onChange:()=>{attempt.updated=Date.now();persist();originalRenderAnswers(readOnly);wireAnswerEditing();}};}
function wireAnswerEditing(){const answers=$('#answers');if(!answers)return;const input=answers.oninput,click=answers.onclick;answers.oninput=ev=>{input?.(ev);window.refreshPaperAnswers();};answers.onclick=ev=>{click?.(ev);window.refreshPaperAnswers();};}
renderAnswers=function(review){originalRenderAnswers(review);wireAnswerEditing();window.refreshPaperAnswers();};
let lastDownloadUrl;
function downloadBlob(blob,name){if(lastDownloadUrl)URL.revokeObjectURL(lastDownloadUrl);lastDownloadUrl=URL.createObjectURL(blob);let panel=$('#answer-download-ready');if(!panel){panel=document.createElement('div');panel.id='answer-download-ready';panel.className='download-ready';panel.setAttribute('role','status');($('.answer-downloads')||$('#view')).append(panel);}panel.replaceChildren();const message=document.createElement('span');message.textContent='Fail on valmis. Kui allalaadimine ei alanud, vali: ';const link=document.createElement('a');link.href=lastDownloadUrl;link.download=name;link.textContent=name;panel.append(message,link);link.click();}
function saveBackup(attempt){const copy=structuredClone(attempt);copy.duration=attempt.duration||0;if(!attempt.created){copy.elapsed=elapsed(attempt);copy.runningSince=null;}downloadBlob(new Blob([JSON.stringify({format:'eksamisamm-answer-backup',version:1,examId:attempt.examId,attempt:copy},null,2)],{type:'application/json'}),`eksamisamm-${attempt.examId}-varukoopia.json`);toast('Vastuste varukoopia on alla laaditud.');}
async function exportAnswered(attempt,button){const text=button.textContent;button.disabled=true;button.textContent='Koostan PDF-i…';try{const bytes=await window.ExamPdfExport.build({attempt:structuredClone(attempt),papers:examById(attempt.examId).papers});downloadBlob(new Blob([bytes],{type:'application/pdf'}),`eksamisamm-${attempt.examId}-vastustega.pdf`);toast('PDF sisaldab sinu teksti ja jooniseid. Pikad või paigutamata vastused on lisalehel.');}catch(err){toast(err.message||'PDF-i eksport ebaõnnestus. Laadi alla vastuste varukoopia.');}finally{button.disabled=false;button.textContent=text;}}
function answerDownloads(attempt){const group=document.createElement('div');group.className='answer-downloads';const pdf=document.createElement('button');pdf.className='primary';pdf.textContent='↓ Laadi vastustega PDF';pdf.onclick=()=>exportAnswered(attempt,pdf);const backup=document.createElement('button');backup.className='secondary';backup.textContent='↓ Vastuste varukoopia';backup.onclick=()=>saveBackup(attempt);group.append(pdf,backup);if(sebPractice){const quit=document.createElement('a');quit.className='secondary seb-quit';quit.href='seb/quit.html';quit.textContent='Välju SEB-ist ↗';group.append(quit);}return group;}
workspace=function(id,review=false){originalWorkspace(id,review);if(activeId!==id)return;const exam=examById(id),attempt=state.drafts[id];window.ExamAnnotations.prepare(attempt);$('.workspace').classList.add('annotated-workspace');$('.workspace-title').after(answerDownloads(attempt));$('.answer-help').textContent=review?'Võrdle PDF-il olevaid vastuseid hindamisjuhendiga ning lisa punktid allpool. Vastuste muutmiseks vali „Muuda vastuseid”.':'Kirjuta või joonista otse PDF-ile. Vastused ilmuvad ka siia ja salvestuvad automaatselt. Olemasoleva vastuse paigutamiseks vali PDF-i tööriistaribal selle number. Jooniste punkte saad lisada vastusereale.';
 const load=()=>{const p=exam.papers[attempt.paper||0];window.loadPaper(p.local||p.url,answeredPdfOptions(attempt,attempt.paper||0,review));$('#paper-fallback').href=p.local||p.url;};load();$('#paper-select').onchange=ev=>{attempt.paper=Number(ev.target.value);persist();load();};
 if(review&&$('#show-guide'))$('#show-guide').onclick=()=>{const links=reviewLinks(exam),guide=links.find(l=>!/suulise/i.test(l.title))||links[0];window.loadPaper(guide.local||guide.url);$('#paper-fallback').href=guide.local||guide.url;};
 const importButton=document.createElement('button');importButton.className='secondary import-answers';importButton.textContent='↑ Taasta vastuste varukoopia';importButton.onclick=()=>chooseBackup(id);$('.answer-downloads').append(importButton);
 if(!sebPractice){const launch=document.createElement('button');launch.className='secondary';launch.textContent='Harjuta Safe Exam Browseris ↗';launch.onclick=()=>showSeb(exam);$('.answer-downloads').append(launch);}
};
finishAttempt=function(){const d=state.drafts[activeId],ink=structuredClone(d?.ink||[]);originalFinish();if(d&&!state.drafts[d.examId]&&state.results[0]?.examId===d.examId){state.results[0].ink=ink;persist();}};
resultDetail=function(id){originalResultDetail(id);const result=state.results.find(r=>r.id===id);if(!result)return;const group=answerDownloads(result);$('.result-actions').after(group);const show=document.createElement('button');show.className='secondary';show.textContent='Vaata vastuseid PDF-il →';show.onclick=()=>{let panel=$('#result-paper');if(!panel){panel=document.createElement('section');panel.className='paper-panel';panel.id='result-paper';panel.innerHTML='<div class="panel-head"><h2>Sinu vastustega eksamitöö</h2></div><div class="paper-choice"><select id="result-part" aria-label="Vaata tulemuse PDF-i osa"></select></div><div id="paper-frame" class="pdf-embed"></div>';group.after(panel);const select=$('#result-part');examById(result.examId).papers.forEach((p,i)=>select.add(new Option(p.title,String(i))));select.onchange=()=>{const i=Number(select.value),p=examById(result.examId).papers[i];window.loadPaper(p.local||p.url,{attempt:result,paper:i,readOnly:true});};}const p=examById(result.examId).papers[0];window.loadPaper(p.local||p.url,{attempt:result,paper:0,readOnly:true});show.textContent='Vastused PDF-il on avatud ✓';};group.append(show);};
function showSeb(exam){const config=new URL(`seb/${exam.id}.seb`,location.href);const launch='sebs://'+config.host+config.pathname;
 modal(`<div class="eyebrow">SEB · iseseisev praktika</div><h2>${esc(exam.name)} ${exam.year}</h2><ol class="help-steps"><li>Paigalda <a href="https://safeexambrowser.org/download_en.html" target="_blank" rel="noopener">Safe Exam Browser</a>, kui see veel puudub.</li><li>Laadi alla eksami seadistusfail ning ava see SEB-iga. Võid kasutada ka käivituslinki.</li><li>Logi vajadusel oma ChatGPT kontole sisse. Harjutusaeg vali pärast eksami avamist.</li><li>Enne väljumist laadi alla vastuste varukoopia.</li></ol><p>Tavabrauseri ja SEB-i vastused salvestuvad eraldi. Pooleli töö jätkamiseks ekspordi varukoopia tavabrauseris ja taasta see SEB-is. See on iseseisva harjutuse seadistus; veebileht ei kontrolli SEB-i eksamivõtit.</p><div class="seb-links"><a class="primary" href="${esc(config.href)}" download="eksamisamm-${exam.id}.seb">↓ Laadi SEB seadistus</a><a class="secondary" href="${esc(launch)}">Ava Safe Exam Browser ↗</a></div><div class="dialog-actions"><button class="secondary" data-close>Tagasi</button></div>`);
}
requestStart=function(id){if(!examById(id))return;originalStart(id);const dlg=$('#dialog');if(!dlg.open||!$('#begin'))return;const intro=dlg.querySelector('p');intro.textContent='Kirjuta ja joonista otse originaalsele eksamitööle. Vastused salvestuvad ning saad alla laadida oma vastustega PDF-i.';
 if(sebPractice){const timed=dlg.querySelector('input[value="timed"]');timed.checked=true;$('#minutes-wrap').hidden=false;}else{const button=document.createElement('button');button.className='secondary seb-start';button.textContent='Harjuta Safe Exam Browseris ↗';button.onclick=()=>{closeModal();showSeb(examById(id));};$('.dialog-actions',dlg).before(button);}
};
function validateBackup(data,expectedExam){if(data?.format!=='eksamisamm-answer-backup'||data.version!==1||!examById(data.examId)||data.examId!==data.attempt?.examId)throw Error('See ei ole Eksamisammu vastuste varukoopia.');if(expectedExam&&expectedExam!==data.examId)throw Error('Varukoopia kuulub teisele eksamile.');const d=data.attempt,e=examById(data.examId);if(!Array.isArray(d.answers)||d.answers.length<1||d.answers.length>1000||!['free','timed'].includes(d.mode))throw Error('Varukoopia andmed ei sobi.');for(const answer of d.answers){if(typeof answer.text!=='string'||answer.text.length>200000||typeof answer.label!=='string'||answer.label.length>30)throw Error('Vastuserida ei sobi.');const a=answer.annotation;if(a&&(!Number.isInteger(a.paper)||a.paper<0||a.paper>=e.papers.length||!Number.isInteger(a.page)||a.page<1||a.page>(e.papers[a.paper].pageCount||200)||!['x','y','w','h'].every(k=>Number.isFinite(a[k])&&a[k]>=0&&a[k]<=1)||a.w<=0||a.h<=0||a.x+a.w>1.001||a.y+a.h>1.001||!Number.isFinite(a.fontSize)||a.fontSize<8||a.fontSize>48))throw Error('PDF-i vastuse asukoht ei sobi.');answer.flag=!!answer.flag;answer.earned=answer.earned??'';answer.max=answer.max??'';answer.id=window.ExamAnnotations.uid();}
 if(d.ink&&!Array.isArray(d.ink))throw Error('Jooniste andmed ei sobi.');if((d.ink||[]).length>5000)throw Error('Varukoopias on liiga palju jooni.');for(const s of d.ink||[]){if(!Number.isInteger(s.paper)||s.paper<0||s.paper>=e.papers.length||!Number.isInteger(s.page)||s.page<1||s.page>(e.papers[s.paper].pageCount||200)||!Array.isArray(s.points)||s.points.length>10000||!s.points.every(p=>Array.isArray(p)&&p.length===2&&p.every(n=>Number.isFinite(n)&&n>=0&&n<=1))||!Number.isFinite(s.width)||s.width<.5||s.width>20)throw Error('PDF-i joonise andmed ei sobi.');}
 if(!Number.isFinite(d.elapsed)||d.elapsed<0||!Number.isFinite(d.duration)||d.duration<0||d.duration>36000)throw Error('Taimeri andmed ei sobi.');d.runningSince=null;d.updated=Date.now();d.status=d.created||d.status==='review'?'review':'practice';d.paper=Number.isInteger(d.paper)&&d.paper>=0&&d.paper<e.papers.length?d.paper:0;d.note=typeof d.note==='string'?d.note.slice(0,200000):'';delete d.created;delete d.score;return d;
}
function chooseBackup(expectedExam){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.hidden=true;document.body.append(input);input.oncancel=()=>input.remove();input.setAttribute('aria-label','Vali vastuste varukoopia');input.onchange=async()=>{const file=input.files[0];input.remove();if(!file)return;try{if(file.size>4*1024*1024)throw Error('Varukoopia on liiga suur (kuni 4 MB).');const draft=validateBackup(JSON.parse(await file.text()),expectedExam),exam=examById(draft.examId);modal(`<h2>Taasta ${esc(exam.name)} ${exam.year}?</h2><p>${draft.answers.length} vastuserida ja ${(draft.ink||[]).length} joonist. ${state.drafts[draft.examId]?'Selle eksami praegune pooleli töö asendatakse. Vajadusel varunda see enne taastamist.':'Harjutus jätkub varukoopias salvestatud kohast.'}</p><div class="dialog-actions"><button class="secondary" data-close>Tagasi</button><button class="primary" id="restore-confirm">Taasta vastused →</button></div>`,()=>{$('#restore-confirm').onclick=()=>{const running=state.drafts[activeId];if(running)pauseDraft(running);state.drafts[draft.examId]=draft;persist();closeModal();go(`${draft.status}/${draft.examId}`);toast('Vastused ja PDF-i joonised taastatud.');};});}catch(err){toast(err.message||'Varukoopiat ei saanud lugeda.');}};input.click();}
function sebLanding(){window.stopPaper?.();clearInterval(tick);tick=null;if(activeId&&state.drafts[activeId])pauseDraft(state.drafts[activeId]);activeId=null;route='seb';const e=examById(sebExamId);$('#breadcrumb').textContent='SEB harjutus';if(!e){$('#view').innerHTML='<div class="empty"><h2>Eksami seadistus ei sobi.</h2><p>Ava eksami seadistusfail uuesti.</p><a class="secondary" href="seb/quit.html">Välju SEB-ist ↗</a></div>';return;}
 $('#view').innerHTML=`${header(`${e.name} ${e.year}`,'Vasta ülesannetele, vali harjutusaeg ning alusta, kui oled valmis.')}<section class="seb-landing"><div class="eyebrow">Safe Exam Browser · praktika</div><h2>Sinu eksam. Sinu keskendumine.</h2><p>Vastused salvestuvad selle brauseri andmetesse. SEB-ist väljumise eel laadi alla vastuste varukoopia. Koolieksami turvakontrolli see harjutus ei asenda.</p><div class="answer-downloads"><button class="primary" id="seb-begin">${state.drafts[e.id]?'Jätka harjutust':'Vali aeg ja alusta'} →</button><button class="secondary" id="seb-restore">↑ Taasta vastuste varukoopia</button><a class="secondary" href="seb/quit.html">Välju SEB-ist ↗</a></div></section>`;$('#seb-begin').onclick=()=>requestStart(e.id);$('#seb-restore').onclick=()=>chooseBackup(e.id);window.scrollTo(0,0);
}
renderRoute=function(){if(!db.exams.length)return;const hash=location.hash.slice(1);if(sebPractice&&(!hash||['exams','saved','results'].includes(hash))){sebLanding();return;}originalRenderRoute();if(!sebPractice&&['exams','saved','results'].includes(route)&&!$('#library-restore')){const b=document.createElement('button');b.id='library-restore';b.className='secondary library-restore';b.textContent='↑ Taasta vastuste varukoopia';b.onclick=()=>chooseBackup();$('#view').append(b);}};
if(db.exams.length)renderRoute();
