'use strict';
const M=window.MathAnswerModel,mathWorkspaceBefore=workspace,mathResultBefore=resultDetail,mathStartBefore=requestStart,mathCardBefore=card;
const isMath=id=>!!window.MathExams[id];
card=function(e){return mathCardBefore(e).replace('<span class="mini-badge">PDF</span>',isMath(e.id)?'<span class="mini-badge interactive-badge">Interaktiivne</span>':'<span class="mini-badge">PDF</span>');};
requestStart=function(id){mathStartBefore(id);if(isMath(id)&&$('#dialog').open&&$('#begin')){$('#dialog p').textContent='Lahenda ülesandeid ükshaaval. Vastuseväljad ja lahenduskäik on kohe ülesande juures. Ülesanded 1–5 ning üks valikülesanne annavad kokku 50 punkti.';}};
workspace=function(id,review=false){if(!isMath(id))return mathWorkspaceBefore(id,review);const d=state.drafts[id];if(!d)return;activeId=id;M.prepare(d,window.MathExams[id]);persist();mathExam(d,review,false);};
resultDetail=function(id){const r=state.results.find(r=>r.id===id);if(!r?.mathExamVersion)return mathResultBefore(id);mathExam(structuredClone(r),true,true);};
function mathExam(d,review,result){
 window.stopPaper?.();clearInterval(tick);tick=null;
 const exam=examById(d.examId),paper=window.MathExams[d.examId];M.prepare(d,paper);
 const save=()=>{if(result)return;d.updated=Date.now();persist();};
 const legacy=d.answers.filter(a=>!a.mathQuestion&&a.text?.trim());
 const selected=()=>M.selected(d),question=()=>paper.questions[d.mathCurrent-1];
 const submittedScore=result?d.score:null;
 $('#view').innerHTML=`<div class="math-shell"><button class="back" ${result?'data-results':'data-back'}>← ${result?'Tagasi tulemustesse':'Tagasi eksamite juurde'}</button><div class="math-heading"><div><div class="eyebrow">${result?'Salvestatud katse':review?'Vaata oma töö üle':'Interaktiivne eksam'}</div><h1>Matemaatika <span class="year-sticker">${exam.year}</span></h1><p>${result?'Sinu vastused, lahenduskäigud ja joonised.':'Ülesanne. Sinu mõttekäik. Sinu vastus. Kõik ühes kohas.'}</p></div><span class="math-total">${submittedScore?.complete?submittedScore.percent+'%':'50'}<small>${submittedScore?.complete?'enesehinnang':'punkti kokku'}</small></span></div>
 ${result?`<div class="math-notice">${d.score.graded}/6 ülesannet enesehinnatud · ${d.score.earned}/50 punkti · ${timeText(d.elapsed)}</div>`:review?'<div class="math-notice"><strong>Vastused on ülevaatuseks valmis.</strong> Võrdle hindamisjuhendiga ja lisa igale ülesandele punktid. <button class="secondary" id="math-edit">Muuda vastuseid</button></div>':`<div class="timerbar math-timer"><div class="timer" id="timer"></div><span class="saving" id="save-state">✓ Salvestatud brauserisse</span><button class="secondary" id="pause">${d.runningSince?'Ⅱ Peata':'▷ Jätka'}</button></div>`}
 <div class="math-layout"><aside class="math-map"><div class="math-map-heading"><h2>Sinu ülesanded</h2><span id="math-progress"></span></div><nav class="math-question-nav" aria-label="Eksami ülesanded">${paper.questions.map(q=>`<button data-math-question="${q.number}" aria-label="Ülesanne ${q.number}: ${esc(q.title)}"><span class="math-num">${q.number}</span><span>${esc(q.title)}<small>${q.points} punkti${q.number>5?' · valikülesanne':''}</small></span><span class="math-state" aria-hidden="true"></span></button>`).join('')}</nav><fieldset class="math-choice"><legend>Valin lahendamiseks</legend><label><input type="radio" name="math-choice" value="6" ${d.mathChoice===6?'checked':''} ${review?'disabled':''}> Ülesanne 6</label><label><input type="radio" name="math-choice" value="7" ${d.mathChoice===7?'checked':''} ${review?'disabled':''}> Ülesanne 7</label></fieldset><p class="math-map-note">Ülesanded 1–5 on kohustuslikud. Ülesannetest 6 ja 7 läheb tulemusse üks.</p>${!result?`<button class="primary" id="math-submit">${review?'Salvesta tulemus ✓':'Esita vastused →'}</button>`:''}</aside><section id="math-question" class="math-question" aria-label="Praegune ülesanne"></section></div>
 <details class="math-resources"><summary>Eksami failid ja varukoopia</summary><div class="math-resource-actions"><button class="secondary" id="math-backup">↓ Vastuste varukoopia</button>${!result?'<button class="secondary" id="math-restore">↑ Taasta varukoopia</button>':''}<button class="secondary" id="math-export">↓ Vastused tekstina</button><a class="secondary" href="${esc(exam.papers[0].local)}" target="_blank" rel="noopener">Originaalne eksamitöö ↗</a>${!sebPractice?'<button class="secondary" id="math-seb">Harjuta Safe Exam Browseris ↗</button>':'<a class="secondary" href="seb/quit.html">Välju SEB-ist ↗</a>'}</div></details>
 ${legacy.length||d.ink?.length?`<details class="math-resources"><summary>Varasema PDF-vaate vastused on alles</summary><p>Varasemad vastused säilivad siin ja varukoopias. Uued vastuseväljad on ülesannete juures.</p>${legacy.map(a=>`<h3>Ülesanne ${esc(a.label)}</h3><pre>${esc(a.text)}</pre>`).join('')}<button class="secondary" id="math-legacy-pdf">↓ Varasemate märkmetega PDF</button></details>`:''}</div>`;
 function status(){const done=selected().filter(a=>M.complete(a,paper.questions[a.mathQuestion-1])).length;$('#math-progress').textContent=done+'/6 täidetud';document.querySelectorAll('[data-math-question]').forEach(b=>{const n=Number(b.dataset.mathQuestion),a=M.row(d,n),q=paper.questions[n-1],active=n===d.mathCurrent;b.setAttribute('aria-current',active?'step':'false');b.classList.toggle('is-current',active);b.classList.toggle('is-answered',M.complete(a,q));b.classList.toggle('not-selected',n>5&&n!==d.mathChoice);b.querySelector('.math-state').textContent=a.flag?'⚑':M.complete(a,q)?'✓':M.started(a)?'•':'';});}
 function switchQuestion(n,focus=true){d.mathCurrent=n;save();drawQuestion();status();if(focus){$('#math-question-title').focus({preventScroll:true});$('#math-question').scrollIntoView({behavior:'auto',block:'start'});}}
 function drawQuestion(){const q=question(),a=M.row(d,q.number),optional=q.number>5&&q.number!==d.mathChoice;
  $('#math-question').innerHTML=`<div class="math-question-head"><div><div class="eyebrow">${q.number>5?'Valikülesanne':'Kohustuslik ülesanne'} · ${q.points} punkti</div><h2 id="math-question-title" tabindex="-1">${q.number}. ${esc(q.title)}</h2></div><button class="secondary math-flag" id="math-flag" aria-pressed="${!!a.flag}" ${result?'disabled':''}>${a.flag?'⚑ Märgitud':'⚐ Märgi hilisemaks'}</button></div>${optional?`<div class="math-optional">See valikülesanne ei lähe praegu sinu tulemusse.${!review?` <button id="math-choose-current" class="secondary">Valin ülesande ${q.number}</button>`:''}</div>`:''}
  <div class="math-prompt-wrap"><div class="math-prompt ${q.draw?'has-drawing':''}" style="aspect-ratio:${q.width}/${q.height}"><img src="${q.image}" width="${q.width}" height="${q.height}" alt="${exam.year}. aasta matemaatikaeksami ülesanne ${q.number}: ${esc(q.title)}. Algne ülesandetekst, valemid ja joonised." draggable="false">${q.draw?`<svg id="math-drawing" viewBox="0 0 1000 ${Math.round(q.height/q.width*1000)}" aria-label="Ülesande ${q.number} joonis" role="img"></svg>`:''}</div></div>
  ${q.draw?`<div class="math-draw-help"><p>${review?'Sinu salvestatud joonis.':'Joonista otse ülalolevale joonisele hiire, puutepliiatsi või sõrmega. Klaviatuuriga võid kirjeldada joonist lahenduskäigu väljal.'}</p>${!review?'<button class="secondary" id="math-undo">↶ Võta viimane joon tagasi</button>':''}</div>`:''}
  <div class="math-answer-form"><h3>Sinu vastused</h3><p class="math-input-hint">Murru võid kirjutada kujul 1/2, astme kujul x^2. Lisa vajadusel täpne väärtus või ühik.</p><div class="math-fields">${q.fields.map(f=>`<label class="${f.long?'wide':''}">${esc(f.label)}${f.long?`<textarea data-math-field="${f.id}" aria-label="${esc(f.label)}" rows="3" ${review?'readonly':''}>${esc(a.mathValues[f.id])}</textarea>`:`<input type="text" data-math-field="${f.id}" aria-label="${esc(f.label)}" value="${esc(a.mathValues[f.id])}" autocomplete="off" spellcheck="false" ${review?'readonly':''}>`}</label>`).join('')}</div><label class="math-working">Lahenduskäik ja põhjendused<textarea id="math-working" rows="5" placeholder="Kirjuta siia arvutused ja selgitused…" ${review?'readonly':''}>${esc(a.mathWork)}</textarea></label>
  ${review?`<div class="math-assessment"><h3>Enesehindamine</h3><p>Kontrolli lahendust ametliku juhendi järgi. Vastuseid ei hinnata automaatselt.</p><button class="secondary" id="math-guide">Ava hindamisjuhend siin ↓</button><div id="math-guide-view" hidden><div id="paper-frame" class="pdf-embed"></div></div><label>Saadud punktid (0–${q.points})<input id="math-points" aria-label="Ülesande ${q.number} saadud punktid" type="number" min="0" max="${q.points}" step="0.5" value="${esc(a.earned)}" ${result||optional?'readonly':''}></label><p id="math-score-error" role="status"></p>${optional?'<p>Seda ülesannet ei arvestata tulemuses.</p>':''}</div>`:''}</div><div class="math-question-bottom"><button class="secondary" id="math-prev" ${q.number===1?'disabled':''}>← Eelmine</button><span>${q.number} / 7</span><button class="primary" id="math-next">${q.number===7?(review?'Ülevaate algusesse ↑':'Esita vastused →'):'Järgmine ülesanne →'}</button></div>`;
  $('#math-flag').onclick=()=>{a.flag=!a.flag;save();$('#math-flag').textContent=a.flag?'⚑ Märgitud':'⚐ Märgi hilisemaks';$('#math-flag').setAttribute('aria-pressed',a.flag);status();};
  const update=()=>{M.sync(a,q);save();status();};
  document.querySelectorAll('[data-math-field]').forEach(input=>input.oninput=()=>{if(review)return;a.mathValues[input.dataset.mathField]=input.value;update();});
  $('#math-working').oninput=ev=>{if(review)return;a.mathWork=ev.target.value;update();};
  $('#math-prev').onclick=()=>switchQuestion(q.number-1);
  $('#math-next').onclick=()=>q.number<7?switchQuestion(q.number+1):review?switchQuestion(1):submit();
  if($('#math-choose-current'))$('#math-choose-current').onclick=()=>{d.mathChoice=q.number;save();document.querySelector(`input[name="math-choice"][value="${q.number}"]`).checked=true;drawQuestion();status();};
  if(review){$('#math-guide').onclick=()=>{const panel=$('#math-guide-view');panel.hidden=!panel.hidden;if(!panel.hidden){const guide=reviewLinks(exam)[0];window.loadPaper(guide.local||guide.url);}};$('#math-points').oninput=ev=>{if(result||optional)return;a.earned=ev.target.value;save();$('#math-score-error').textContent=M.score(d).invalid?'Sisesta punktid ülesande lubatud vahemikus.':'';};}
  if(q.draw)mathDrawing($('#math-drawing'),a,review,update);
 }
 function submit(){if(result)return;if(review){const s=M.score(d);if(s.invalid){toast('Kontrolli punkte: tulemus peab jääma 0 ja ülesande maksimumpunktide vahele.');const bad=selected().find(a=>a.earned!==''&&(!Number.isFinite(Number(a.earned))||Number(a.earned)<0||Number(a.earned)>a.max));if(bad)switchQuestion(bad.mathQuestion);return;}pauseDraft(d);const id=crypto.randomUUID();state.results.unshift({...structuredClone(d),id,created:Date.now(),elapsed:elapsed(d),runningSince:null,score:s});delete state.drafts[d.examId];persist();go('result/'+id);toast('Sinu vastused ja joonised on salvestatud.');return;}
  const incomplete=selected().filter(a=>!M.complete(a,paper.questions[a.mathQuestion-1]));modal(`<h2>Esitad vastused?</h2><p>${incomplete.length?`Veel täiendamist vajavad ülesanded: ${incomplete.map(a=>a.mathQuestion).join(', ')}. Võid esitada ka pooleli vastused.`:'Kõigi valitud ülesannete vastuseväljad on täidetud.'} Vastuseid saad ülevaatuse ajal veel muuta.</p><div class="dialog-actions"><button class="secondary" data-close>Jätkan lahendamist</button><button class="primary" id="math-confirm">Esita ja vaata üle →</button></div>`,()=>{$('#math-confirm').onclick=()=>{pauseDraft(d);d.status='review';save();closeModal();go('review/'+d.examId);};});
 }
 document.querySelectorAll('[data-math-question]').forEach(b=>b.onclick=()=>{window.stopPaper?.();switchQuestion(Number(b.dataset.mathQuestion));});
 document.querySelectorAll('input[name="math-choice"]').forEach(input=>input.onchange=()=>{if(review)return;d.mathChoice=Number(input.value);save();drawQuestion();status();});
 if(!result)$('#math-submit').onclick=submit;
 $('#math-backup').onclick=()=>saveBackup(d);$('#math-export').onclick=()=>{const s=M.score(d),text=`Eksamisamm · Matemaatika ${exam.year}\nValikülesanne: ${d.mathChoice}\nEnesehindamine: ${s.earned}/50 punkti; hinnatud ${s.graded}/6 ülesannet\n\n`+selected().map(a=>`Ülesanne ${a.mathQuestion}\n${a.text||'(vastus puudub)'}\nPunktid: ${a.earned===''?'—':a.earned}/${a.max}`).join('\n\n');downloadBlob(new Blob([text],{type:'text/plain;charset=utf-8'}),`eksamisamm-${d.examId}-vastused.txt`);};
 if($('#math-restore'))$('#math-restore').onclick=()=>chooseBackup(d.examId);
 if($('#math-seb'))$('#math-seb').onclick=()=>showSeb(exam);
 if($('#math-legacy-pdf'))$('#math-legacy-pdf').onclick=ev=>exportAnswered(d,ev.target);
 if(!review){$('#pause').onclick=()=>{if(d.runningSince)pauseDraft(d);else d.runningSince=Date.now();save();$('#pause').textContent=d.runningSince?'Ⅱ Peata':'▷ Jätka';clockUpdate();};clockUpdate();tick=setInterval(clockUpdate,1000);}
 if(review&&!result)$('#math-edit').onclick=()=>{if(d.mode==='timed'&&elapsed(d)>=d.duration)d.mode='free';d.status='practice';save();go('practice/'+d.examId);};
 drawQuestion();status();
}
function mathDrawing(svg,a,readOnly,changed){
 const h=svg.viewBox.baseVal.height;let current=null;
 const draw=()=>{svg.replaceChildren();for(const stroke of [...a.mathDrawing,...(current?[current]:[])]){const path=document.createElementNS('http://www.w3.org/2000/svg','polyline');path.setAttribute('points',stroke.map(p=>`${p[0]*1000},${p[1]*h}`).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#1d4ed8');path.setAttribute('stroke-width','3');path.setAttribute('stroke-linecap','round');path.setAttribute('stroke-linejoin','round');svg.append(path);}};
 draw();if(readOnly){svg.style.pointerEvents='none';return;}
 const point=ev=>{const r=svg.getBoundingClientRect();return[Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height))];};
 svg.onpointerdown=ev=>{if(ev.button!==0)return;ev.preventDefault();svg.setPointerCapture(ev.pointerId);const p=point(ev);current=[p,p];draw();};
 svg.onpointermove=ev=>{if(!current)return;current.push(point(ev));draw();};
 const finish=()=>{if(current){a.mathDrawing.push(current);current=null;changed();draw();}};
 svg.onpointerup=finish;svg.onpointercancel=finish;
 $('#math-undo').onclick=()=>{a.mathDrawing.pop();changed();draw();};
}
if(db.exams.length)renderRoute();
