(function(){
 'use strict';
 let library,current,resizeTimer;
 const find=s=>document.querySelector(s),A=window.ExamAnnotations;
 async function pdfLibrary(){if(!library)library=import('./vendor/pdf.mjs').then(lib=>{lib.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.mjs';return lib;});return library;}
 const svgNS='http://www.w3.org/2000/svg';
 window.stopPaper=function(){if(current){current.cancelled=true;current.task?.cancel();current.loading?.destroy();current=null;}};
 window.refreshPaperAnswers=function(){current?.refresh?.();};
 window.loadPaper=async function(url,options={}){
  const container=find('#paper-frame');if(!container)return;
  const viewer={container,url,page:options.page||1,zoom:options.zoom||1,pdf:null,cancelled:false,tool:options.readOnly?'select':'text',fontSize:14,options,viewport:null,stroke:null};
  window.stopPaper();current=viewer;
  const editable=!!options.attempt&&!options.readOnly;
  const attempt=options.attempt?A.prepare(options.attempt):null;
  const paper=options.paper??0;
  const changed=()=>options.onChange?.();
  container.innerHTML='<div class="pdf-loading" role="status">Laen eksamitööd…</div>';
  try{
   const lib=await pdfLibrary();if(current!==viewer)return;
   viewer.loading=lib.getDocument({url,useSystemFonts:true,isEvalSupported:false});viewer.pdf=await viewer.loading.promise;if(current!==viewer)return;
   container.innerHTML=`<div class="pdf-toolbar"><button id="pdf-prev" aria-label="Eelmine PDF-leht">←</button><span id="pdf-page" aria-live="polite"></span><button id="pdf-next" aria-label="Järgmine PDF-leht">→</button><span class="pdf-spacer"></span><button id="pdf-minus" aria-label="Vähenda PDF-i">−</button><button id="pdf-plus" aria-label="Suurenda PDF-i">+</button></div>${editable?`<div class="annotation-toolbar" role="group" aria-label="PDF-i vastamise tööriistad"><button data-tool="text" aria-pressed="true">T Tekst</button><button data-tool="pen" aria-pressed="false">✎ Pliiats</button><button data-tool="select" aria-pressed="false">↖ Vali</button><button id="ink-undo">↶ Võta joon tagasi</button><label>Teksti suurus <select id="annotation-size" aria-label="PDF-i teksti suurus"><option value="12">12</option><option value="14" selected>14</option><option value="18">18</option><option value="24">24</option></select></label><label>Paiguta vastus <select id="annotation-answer" aria-label="PDF-ile paigutatav vastus"></select></label><button id="annotation-keyboard">+ Lisa tekstikast</button></div><p class="annotation-hint" id="annotation-hint" role="status">Klõpsa vastuse kohal PDF-il ja kirjuta. Tekstikasti saad liigutada noolekäepidemest ning suurust muuta alumisest nurgast.</p>`:''}<div class="pdf-scroll"><div class="pdf-stage"><canvas id="pdf-canvas" role="img" aria-label="Eksamitöö lehekülg"></canvas><svg class="ink-layer" aria-hidden="true"></svg><div class="answer-layer"></div></div></div><details class="pdf-access"><summary>Lehekülje tekst (ligipääsetav vaade)</summary><div id="pdf-text"></div></details>`;
   const stage=find('.pdf-stage'),canvas=find('#pdf-canvas'),layer=find('.answer-layer'),ink=find('.ink-layer');
   function localPoint(ev){const r=stage.getBoundingClientRect();return[A.clamp((ev.clientX-r.left)/r.width),A.clamp((ev.clientY-r.top)/r.height)];}
   function onPage(annotation){return annotation&&annotation.paper===paper&&annotation.page===viewer.page;}
   function drawInk(){ink.replaceChildren();if(!attempt)return;const strokes=attempt.ink.filter(onPage);if(viewer.stroke)strokes.push(viewer.stroke);for(const stroke of strokes){const path=document.createElementNS(svgNS,'polyline');path.setAttribute('points',stroke.points.map(([x,y])=>`${x*viewer.viewport.width},${y*viewer.viewport.height}`).join(' '));path.setAttribute('stroke','#000');path.setAttribute('fill','none');path.setAttribute('stroke-width',String((stroke.width||2)*viewer.viewport.scale));path.setAttribute('stroke-linecap','round');path.setAttribute('stroke-linejoin','round');ink.append(path);}}
   function answerChoices(){const select=find('#annotation-answer');if(!select)return;const previous=select.value;select.replaceChildren(new Option('Uus vastus',''));for(const answer of attempt.answers.filter(a=>!a.annotation))select.add(new Option(`Ülesanne ${answer.label}${answer.text?' · olemasolev vastus':''}`,answer.id));if([...select.options].some(o=>o.value===previous))select.value=previous;}
   function setTool(tool){viewer.tool=tool;stage.dataset.tool=tool;container.querySelectorAll('[data-tool]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tool===tool)));find('#annotation-hint').textContent=tool==='pen'?'Joonista PDF-ile hiire, puutepliiatsi või sõrmega. „Võta joon tagasi” eemaldab selle osa viimase joone.':tool==='select'?'Muuda teksti kastis või liiguta kasti noolekäepidemest. Lehel liikumiseks kasuta kerimisriba.':'Klõpsa vastuse kohal PDF-il ja kirjuta. Tekstikasti saad liigutada noolekäepidemest ning suurust muuta alumisest nurgast.';}
   function refresh(){if(!viewer.viewport||viewer.cancelled)return;answerChoices();layer.replaceChildren();if(attempt){for(const answer of attempt.answers.filter(a=>onPage(a.annotation))){const annotation=answer.annotation,box=document.createElement('div');box.className='pdf-answer';box.dataset.answerId=answer.id;box.style.left=`${annotation.x*100}%`;box.style.top=`${annotation.y*100}%`;box.style.width=`${annotation.w*100}%`;box.style.height=`${annotation.h*100}%`;
     if(options.readOnly){box.classList.add('read-only');const text=document.createElement('div');text.textContent=answer.text;text.style.fontSize=`${annotation.fontSize*viewer.viewport.scale}px`;text.style.padding=`${4*viewer.viewport.scale}px`;box.append(text);}
     else{
      const handle=document.createElement('button');handle.className='answer-move';handle.type='button';handle.setAttribute('aria-label',`Liiguta ülesande ${answer.label} vastust`);handle.textContent='↔';handle.title='Lohista või kasuta nooleklahve';
      const text=document.createElement('textarea');text.value=answer.text;text.setAttribute('aria-label',`PDF-il: ülesande ${answer.label} vastus`);text.placeholder=`Vastus ${answer.label}…`;text.style.fontSize=`${annotation.fontSize*viewer.viewport.scale}px`;text.style.padding=`${4*viewer.viewport.scale}px`;
      text.oninput=()=>{answer.text=text.value;changed();};
      text.onblur=()=>{if(!text.style.width&&!text.style.height)return;const size=text.getBoundingClientRect(),r=stage.getBoundingClientRect();annotation.w=A.clamp(size.width/r.width,.06,1-annotation.x);annotation.h=A.clamp(size.height/r.height,.025,1-annotation.y);box.style.width=`${annotation.w*100}%`;box.style.height=`${annotation.h*100}%`;text.style.width='';text.style.height='';changed();};
      handle.onkeydown=ev=>{const keys={ArrowLeft:[-.005,0],ArrowRight:[.005,0],ArrowUp:[0,-.005],ArrowDown:[0,.005]};if(keys[ev.key]){ev.preventDefault();A.move(annotation,annotation.x+keys[ev.key][0],annotation.y+keys[ev.key][1]);box.style.left=`${annotation.x*100}%`;box.style.top=`${annotation.y*100}%`;changed();}};
      handle.onpointerdown=ev=>{if(ev.button!==0)return;ev.preventDefault();ev.stopPropagation();const start=localPoint(ev),original=[annotation.x,annotation.y];handle.setPointerCapture(ev.pointerId);handle.onpointermove=e=>{const p=localPoint(e);A.move(annotation,original[0]+p[0]-start[0],original[1]+p[1]-start[1]);box.style.left=`${annotation.x*100}%`;box.style.top=`${annotation.y*100}%`;};handle.onpointerup=()=>{handle.onpointermove=null;changed();};handle.onpointercancel=()=>{handle.onpointermove=null;changed();};};
      const remove=document.createElement('button');remove.className='answer-unplace';remove.type='button';remove.setAttribute('aria-label',`Eemalda ülesande ${answer.label} kast PDF-ilt, säilita vastus`);remove.textContent='×';remove.onclick=()=>{delete answer.annotation;changed();refresh();};box.append(handle,remove,text);
     }layer.append(box);
   }}drawInk();}
   viewer.refresh=refresh;
   function addText(x,y){const choice=find('#annotation-answer')?.value;let answer=choice?attempt.answers.find(a=>a.id===choice):attempt.answers.find(a=>!a.annotation&&!a.text.trim());if(!answer){answer={id:A.uid(),label:String(attempt.answers.length+1),text:'',flag:false,earned:'',max:''};attempt.answers.push(answer);}const base=viewer.viewport;answer.annotation={paper,page:viewer.page,...A.box(x,y,base.width/base.scale,base.height/base.scale,viewer.fontSize)};changed();refresh();layer.querySelector(`[data-answer-id="${answer.id}"] textarea`)?.focus();}
   const render=async()=>{if(viewer.cancelled)return;viewer.task?.cancel();const pageNumber=viewer.page,page=await viewer.pdf.getPage(pageNumber);if(viewer.cancelled||pageNumber!==viewer.page)return;const scroll=find('.pdf-scroll');if(!scroll)return;const width=Math.max(240,scroll.clientWidth-32);viewer.viewport=page.getViewport({scale:width/page.getViewport({scale:1}).width*viewer.zoom});const viewport=viewer.viewport,dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.floor(viewport.width*dpr);canvas.height=Math.floor(viewport.height*dpr);canvas.style.width=stage.style.width=viewport.width+'px';canvas.style.height=stage.style.height=viewport.height+'px';canvas.setAttribute('aria-label','Eksamitöö lehekülg '+pageNumber);ink.setAttribute('viewBox',`0 0 ${viewport.width} ${viewport.height}`);find('#pdf-page').textContent=pageNumber+' / '+viewer.pdf.numPages;find('#pdf-prev').disabled=pageNumber===1;find('#pdf-next').disabled=pageNumber===viewer.pdf.numPages;find('#pdf-minus').disabled=viewer.zoom<=.75;find('#pdf-plus').disabled=viewer.zoom>=3;find('#pdf-text').textContent='Laen teksti…';refresh();viewer.task=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:dpr===1?null:[dpr,0,0,dpr,0,0]});try{await viewer.task.promise;const content=await page.getTextContent();if(!viewer.cancelled&&pageNumber===viewer.page)find('#pdf-text').textContent=content.items.map(i=>i.str+(i.hasEOL?'\n':' ')).join('');}catch(err){if(err.name!=='RenderingCancelledException')throw err;}};
   find('#pdf-prev').onclick=()=>{if(viewer.page>1){viewer.page--;render();}};find('#pdf-next').onclick=()=>{if(viewer.page<viewer.pdf.numPages){viewer.page++;render();}};find('#pdf-minus').onclick=()=>{viewer.zoom=Math.max(.75,viewer.zoom-.25);render();};find('#pdf-plus').onclick=()=>{viewer.zoom=Math.min(3,viewer.zoom+.25);render();};
   if(editable){
    stage.dataset.tool=viewer.tool;
    container.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
    find('#annotation-size').onchange=ev=>{viewer.fontSize=Number(ev.target.value);};
    find('#annotation-keyboard').onclick=()=>{setTool('text');addText(.12,.2);};
    find('#ink-undo').onclick=()=>{const i=attempt.ink.map(s=>s.paper===paper).lastIndexOf(true);if(i>=0){attempt.ink.splice(i,1);changed();drawInk();}};
    stage.onpointerdown=ev=>{if(ev.button!==0||ev.target.closest('.pdf-answer'))return;const p=localPoint(ev);if(viewer.tool==='text'){ev.preventDefault();addText(...p);}else if(viewer.tool==='pen'){ev.preventDefault();stage.setPointerCapture(ev.pointerId);viewer.stroke={id:A.uid(),paper,page:viewer.page,width:2,points:[p,p]};drawInk();}};
    stage.onpointermove=ev=>{if(!viewer.stroke)return;ev.preventDefault();const p=localPoint(ev),last=viewer.stroke.points.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])>.001){viewer.stroke.points.push(p);drawInk();}};
    const finishStroke=()=>{if(viewer.stroke){attempt.ink.push(viewer.stroke);viewer.stroke=null;changed();drawInk();}};stage.onpointerup=finishStroke;stage.onpointercancel=finishStroke;
   }
   await render();
  }catch(err){if(current!==viewer||viewer.cancelled)return;container.innerHTML='<div class="pdf-loading"><p>Eksamitööd ei saanud siin kuvada.</p><a class="secondary" target="_blank" rel="noopener">Ava PDF uuel vahelehel ↗</a></div>';find('#paper-frame a').href=url;}
 };
 window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(current&&find('#paper-frame'))window.loadPaper(current.url,{...current.options,page:current.page,zoom:current.zoom});},250);});
})();
