'use strict';
const S=window.SubjectAnswerModel,subjectWorkspaceBefore=workspace,subjectResultBefore=resultDetail,subjectStartBefore=requestStart,subjectCardBefore=card;
const isSubject=id=>!!window.SubjectExams[id];
card=function(e){return subjectCardBefore(e).replace('<span class="mini-badge">PDF</span>',isSubject(e.id)?'<span class="mini-badge interactive-badge">Interaktiivne</span>':'<span class="mini-badge">PDF</span>');};
requestStart=function(id){subjectStartBefore(id);if(isSubject(id)&&$('#dialog').open&&$('#begin'))$('#dialog p').textContent='Vasta otse eksamitöö valmis vastuseväljadel. Tabelid, kirjutamisalad ja joonised on samal leheküljel. Vastused salvestuvad automaatselt.';};
workspace=function(id,review=false){if(!isSubject(id))return subjectWorkspaceBefore(id,review);const d=state.drafts[id];if(!d)return;activeId=id;S.prepare(d,window.SubjectExams[id]);persist();subjectExam(d,review,false);};
resultDetail=function(id){const r=state.results.find(r=>r.id===id);if(!r?.subjectExamVersion)return subjectResultBefore(id);subjectExam(structuredClone(r),true,true);};
function subjectExam(d,review,result){
 window.stopPaper?.();clearInterval(tick);tick=null;
 const exam=examById(d.examId),paper=window.SubjectExams[d.examId];S.prepare(d,paper);
 const guides=reviewLinks(exam).slice().sort((a,b)=>Number(/suulise/i.test(a.title))-Number(/suulise/i.test(b.title)));
 const save=()=>{if(result)return;d.updated=Date.now();persist();};
 const page=()=>paper.pages[d.subjectCurrent-1],legacy=d.answers.filter(a=>!a.subjectPage&&a.text?.trim());
 const audio=exam.resources.find(r=>/helifail|audiofail/i.test(r.title));
 $('#view').innerHTML=`<div class="math-shell subject-shell"><button class="back" ${result?'data-results':'data-back'}>← ${result?'Tagasi tulemustesse':'Tagasi eksamite juurde'}</button><div class="math-heading"><div><div class="eyebrow">${result?'Salvestatud katse':review?'Vaata oma töö üle':'Interaktiivne eksam'}</div><h1>${esc(exam.name)} <span class="year-sticker">${exam.year}</span></h1><p>Originaalsed ülesanded. Valmis vastuseväljad. Sinu mõttekäik.</p></div><span class="math-total">${paper.pages.length}<small>lehekülge</small></span></div>
 ${result?`<div class="math-notice">${d.score.graded}/${d.score.total} vastatud lehekülge enesehinnatud · ${d.score.earned}/${d.score.max} punkti · ${timeText(d.elapsed)}<p>See on sinu sisestatud vastuste enesehinnang. Kogu ametliku eksami punktisummat see ei kinnita.</p><button class="secondary" data-start="${d.examId}">Harjuta uuesti →</button></div>`:review?'<div class="math-notice"><strong>Vastused on ülevaatuseks valmis.</strong> Võrdle neid ametliku hindamisjuhendiga. <button class="secondary" id="subject-edit">Muuda vastuseid</button></div>':`<div class="timerbar math-timer"><div class="timer" id="timer"></div><span class="saving" id="save-state"></span><button class="secondary" id="pause">${d.runningSince?'Ⅱ Peata':'▷ Jätka'}</button></div>`}
 ${audio?`<section class="subject-audio audio-block" aria-label="Kuulamisosa"><strong>Kuulamisosa · ametlik helifail</strong><audio controls preload="none" src="${esc(audio.local||audio.url)}"></audio><p>Kuula ja kirjuta vastused eksamitöö väljadele. <a href="${esc(audio.local||audio.url)}" target="_blank" rel="noopener">Ava helifail ↗</a></p></section>`:''}
 ${exam.subject==='history'&&exam.papers.length>2?'<div class="math-notice">Selles arhiivis on kaks II vihiku varianti. Harjuta korraga üht varianti; teise vastuseid ei pea esitama.</div>':''}<div class="math-layout"><aside class="math-map"><div class="math-map-heading"><h2>Sinu eksamitöö</h2><span id="subject-progress"></span></div><nav class="math-question-nav subject-page-nav" aria-label="Eksami leheküljed">${paper.pages.map(p=>`<button data-subject-page="${p.number}" aria-label="${esc(p.title)}"><span class="math-num">${p.number}</span><span>${esc(p.title)}<small>${p.fields.length?'Vastuseväljad':'Tekst, ülesanded või joonis'}</small></span><span class="math-state" aria-hidden="true"></span></button>`).join('')}</nav>${!result?`<button class="primary" id="subject-submit">${review?'Salvesta tulemus ✓':'Esita vastused →'}</button>`:''}</aside><section class="math-question subject-question" id="subject-page" aria-label="Praegune eksamilehekülg"></section></div>
 <details class="math-resources"><summary>Eksami failid ja varukoopia</summary><div class="math-resource-actions"><button class="secondary" id="subject-backup">↓ Vastuste varukoopia</button>${!result?'<button class="secondary" id="subject-restore">↑ Taasta varukoopia</button>':''}<button class="secondary" id="subject-export">↓ Vastused tekstina</button>${exam.papers.map(p=>`<a class="secondary" href="${esc(p.local||p.url)}" target="_blank" rel="noopener">${esc(p.title)} ↗</a>`).join('')}${!sebPractice?'<button class="secondary" id="subject-seb">Harjuta Safe Exam Browseris ↗</button>':'<a class="secondary" href="seb/quit.html">Välju SEB-ist ↗</a>'}</div>${exam.subject==='english'?'<p>Suulise osa õpetaja-, pildi- ja rollimängukaardid leiad allpool ametlike materjalide hulgast. Suulist vastust harjuta vestluskaaslasega.</p>':''}<div class="subject-links">${exam.resources.filter(r=>!/helifail|audiofail/i.test(r.title)).map(r=>`<a href="${esc(r.local||r.url)}" target="_blank" rel="noopener">${esc(r.title)} ↗</a>`).join('')}</div></details>
 ${legacy.length||d.ink?.length?`<details class="math-resources"><summary>Varasema PDF-vaate vastused on alles</summary>${legacy.map(a=>`<h3>Ülesanne ${esc(a.label)}</h3><pre>${esc(a.text)}</pre>`).join('')}<button class="secondary" id="subject-legacy">↓ Varasemate märkmetega PDF</button></details>`:''}</div>`;
 function status(){const done=S.selected(d).filter(a=>a.pageDone).length;$('#subject-progress').textContent=done+'/'+paper.pages.length+' lk valmis';document.querySelectorAll('[data-subject-page]').forEach(b=>{const a=S.row(d,Number(b.dataset.subjectPage)),current=a.subjectPage===d.subjectCurrent;b.classList.toggle('is-current',current);b.classList.toggle('is-answered',a.pageDone);b.setAttribute('aria-current',current?'page':'false');b.querySelector('.math-state').textContent=a.flag?'⚑':a.pageDone?'✓':S.started(a)?'•':'';});}
 function change(n,focus=true){window.stopPaper?.();d.subjectCurrent=n;save();drawPage();status();if(focus){$('#subject-title').focus({preventScroll:true});$('#subject-page').scrollIntoView({block:'start'});}}
 function field(f,a,positioned){const value=a.pageValues[f.id],disabled=review?'disabled':'';const attr=`data-page-field="${f.id}" aria-label="${esc(f.label)}" ${positioned?`style="left:${f.x*100}%;top:${f.y*100}%;width:${f.w*100}%;height:${f.h*100}%"`:''}`;if(f.kind==='check')return `<input type="checkbox" ${attr} ${value?'checked':''} ${disabled}>`;if(f.kind==='long')return `<textarea ${attr} ${review?'readonly':''} spellcheck="false">${esc(value)}</textarea>`;return `<input type="text" ${attr} value="${esc(value)}" autocomplete="off" spellcheck="false" ${review?'readonly':''}>`;}
 function drawPage(){const p=page(),a=S.row(d,p.number);
  $('#subject-page').innerHTML=`<div class="math-question-head"><div><div class="eyebrow">${p.number} / ${paper.pages.length} · ${p.fields.length} valmis vastusevälja</div><h2 id="subject-title" tabindex="-1">${esc(p.title)}</h2></div><button class="secondary math-flag" id="subject-flag" aria-pressed="${a.flag}" ${result?'disabled':''}>${a.flag?'⚑ Märgitud':'⚐ Märgi hilisemaks'}</button></div>
  <div class="subject-instructions"><p>${review?'Sinu salvestatud vastused ja joonised.':'Klõpsa vastusejoonel või tabelilahtris ja kirjuta. Valikukastis märgi vastus. Joonisele saad kirjutada või joonistada hiire või puutepliiatsiga kohe.'}</p><button class="secondary" id="subject-zoom">Suurem vaade</button>${!review?'<button class="secondary" id="subject-undo">↶ Võta viimane joon tagasi</button>':''}</div>
  <div class="subject-sheet-scroll" tabindex="0" aria-label="Eksamitöö lehekülg; vajadusel keri külgsuunas"><div class="subject-sheet" style="aspect-ratio:${p.width}/${p.height}"><img src="${p.image}" width="${p.width}" height="${p.height}" alt="${esc(exam.name)} ${exam.year}, ${esc(p.title)}: algne eksamitöö koos ülesannete, tekstide ja joonistega." draggable="false"><svg id="subject-drawing" viewBox="0 0 1000 ${Math.round(p.height/p.width*1000)}" role="img" aria-label="Selle lehekülje salvestatud joonis"></svg><div class="subject-inline-fields">${p.fields.map(f=>field(f,a,true)).join('')}</div></div></div>
  <div class="math-answer-form"><details class="subject-text-fields"><summary>Vastuseväljad tekstivaates · ${p.fields.length}</summary><p>Samad vastused mugavas tekstivaates. Muudatused salvestuvad ka eksamileheküljele.</p><div class="math-fields">${p.fields.map(f=>`<label class="${f.kind==='long'?'wide':''}">${esc(f.label)}${field(f,a,false)}</label>`).join('')}</div></details><label class="math-working">Mõttekäik ja lisavastused<textarea id="subject-work" rows="5" placeholder="Arvutused, selgitused, pikem vastus või joonise kirjeldus…" ${review?'readonly':''}>${esc(a.pageWork)}</textarea></label><label class="subject-done"><input id="subject-done" type="checkbox" ${a.pageDone?'checked':''} ${review?'disabled':''}> Olen selle lehekülje üle vaadanud ja valmis.</label>
  ${review?`<div class="math-assessment"><h3>Enesehindamine</h3><p>Kontrolli vastuseid ametlikust juhendist. Sisesta ainult selle lehekülje vastuste punktid; üle mitme lehekülje jätkuvat ülesannet ära arvesta kaks korda. Tulemus põhineb sinu sisestatud punktidel.</p><select id="subject-guide-select" aria-label="Vali hindamisjuhend">${guides.map((l,i)=>`<option value="${i}">${esc(l.title)}</option>`).join('')}</select><button class="secondary" id="subject-guide">Ava hindamisjuhend siin ↓</button><div id="subject-guide-view" hidden><div id="paper-frame" class="pdf-embed"></div></div><div class="math-fields"><label>Saadud punktid<input id="subject-earned" aria-label="Saadud punktid" type="number" min="0" step="0.5" value="${esc(a.earned)}" ${result?'readonly':''}></label><label>Võimalikud punktid<input id="subject-max" aria-label="Võimalikud punktid" type="number" min="0" step="0.5" value="${esc(a.max)}" ${result?'readonly':''}></label></div><p id="subject-score-error" role="status"></p></div>`:''}</div><div class="math-question-bottom"><button class="secondary" id="subject-prev" ${p.number===1?'disabled':''}>← Eelmine</button><span>${p.number} / ${paper.pages.length}</span><button class="primary" id="subject-next">${p.number===paper.pages.length?(review?'Ülevaate algusesse ↑':'Esita vastused →'):'Järgmine lehekülg →'}</button></div>`;
  const update=()=>{S.sync(a,p);save();status();};
  document.querySelectorAll('[data-page-field]').forEach(input=>input.oninput=()=>{if(review)return;const f=p.fields.find(f=>f.id===input.dataset.pageField);a.pageValues[f.id]=f.kind==='check'?input.checked:input.value;document.querySelectorAll(`[data-page-field="${f.id}"]`).forEach(other=>{if(other!==input){if(f.kind==='check')other.checked=input.checked;else other.value=input.value;}});update();});
  $('#subject-work').oninput=ev=>{if(review)return;a.pageWork=ev.target.value;update();};
  $('#subject-done').onchange=ev=>{if(review)return;a.pageDone=ev.target.checked;update();};
  $('#subject-flag').onclick=()=>{a.flag=!a.flag;save();$('#subject-flag').textContent=a.flag?'⚑ Märgitud':'⚐ Märgi hilisemaks';$('#subject-flag').setAttribute('aria-pressed',a.flag);status();};
  $('#subject-prev').onclick=()=>change(p.number-1);$('#subject-next').onclick=()=>p.number<paper.pages.length?change(p.number+1):review?change(1):submit();
  $('#subject-zoom').onclick=()=>{const sheet=$('.subject-sheet');sheet.classList.toggle('is-zoomed');$('#subject-zoom').textContent=sheet.classList.contains('is-zoomed')?'Tavaline vaade':'Suurem vaade';};
  if(review){$('#subject-guide').onclick=()=>{const panel=$('#subject-guide-view');panel.hidden=!panel.hidden;if(!panel.hidden){const guide=guides[Number($('#subject-guide-select').value)];if(guide)window.loadPaper(guide.local||guide.url);}};for(const [id,key] of [['subject-earned','earned'],['subject-max','max']])$('#'+id).oninput=ev=>{if(result)return;a[key]=ev.target.value;save();$('#subject-score-error').textContent=S.score(d).invalid?'Sisesta saadud ja võimalikud punktid. Saadud punktid ei saa olla maksimumist suuremad.':'';};}
  subjectDrawing($('#subject-drawing'),a,review,update);
 }
 function submit(){if(result)return;if(review){const s=S.score(d);if(s.invalid){toast('Kontrolli saadud ja võimalikke punkte.');const bad=S.selected(d).find(a=>(a.earned!==''||a.max!=='')&&(a.earned===''||a.max===''||!Number.isFinite(Number(a.earned))||!Number.isFinite(Number(a.max))||Number(a.earned)<0||Number(a.max)<0||Number(a.earned)>Number(a.max)));if(bad)change(bad.subjectPage);return;}pauseDraft(d);const id=crypto.randomUUID();state.results.unshift({...structuredClone(d),id,created:Date.now(),elapsed:elapsed(d),runningSince:null,score:s});delete state.drafts[d.examId];persist();go('result/'+id);toast('Vastused ja joonised on salvestatud.');return;}
  const done=S.selected(d).filter(a=>a.pageDone).length;modal(`<h2>Esitad vastused?</h2><p>${done}/${paper.pages.length} lehekülge on märgitud valmis. Võid esitada ka pooleli töö. Vastused ja joonised jäävad alles ning saad neid ülevaatuses veel muuta.</p><div class="dialog-actions"><button class="secondary" data-close>Jätkan lahendamist</button><button class="primary" id="subject-confirm">Esita ja vaata üle →</button></div>`,()=>{$('#subject-confirm').onclick=()=>{pauseDraft(d);d.status='review';save();closeModal();go('review/'+d.examId);};});
 }
 document.querySelectorAll('[data-subject-page]').forEach(b=>b.onclick=()=>change(Number(b.dataset.subjectPage)));
 if(!result)$('#subject-submit').onclick=submit;
 $('#subject-backup').onclick=()=>saveBackup(d);$('#subject-export').onclick=()=>{const text=`Eksamisamm · ${exam.name} ${exam.year}\n\n`+paper.pages.map(p=>{const a=S.row(d,p.number);return `${p.title}\n${a.text||'(vastus puudub)'}\nPunktid: ${a.earned||'—'}/${a.max||'—'}`;}).join('\n\n');downloadBlob(new Blob([text],{type:'text/plain;charset=utf-8'}),`eksamisamm-${d.examId}-vastused.txt`);};
 if($('#subject-restore'))$('#subject-restore').onclick=()=>chooseBackup(d.examId);
 if($('#subject-seb'))$('#subject-seb').onclick=()=>showSeb(exam);
 if($('#subject-legacy'))$('#subject-legacy').onclick=ev=>exportAnswered(d,ev.target);
 if(!review){$('#pause').onclick=()=>{if(d.runningSince)pauseDraft(d);else d.runningSince=Date.now();save();$('#pause').textContent=d.runningSince?'Ⅱ Peata':'▷ Jätka';clockUpdate();};clockUpdate();tick=setInterval(clockUpdate,1000);}
 if(review&&!result)$('#subject-edit').onclick=()=>{if(d.mode==='timed'&&elapsed(d)>=d.duration)d.mode='free';d.status='practice';save();go('practice/'+d.examId);};
 drawPage();status();persist();
}
function subjectDrawing(svg,a,readOnly,changed){
 const h=svg.viewBox.baseVal.height;let current=null;
 const paint=()=>{svg.replaceChildren();for(const stroke of [...a.pageDrawing,...(current?[current]:[])]){const path=document.createElementNS('http://www.w3.org/2000/svg','polyline');path.setAttribute('points',stroke.map(p=>`${p[0]*1000},${p[1]*h}`).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke','#1d4ed8');path.setAttribute('stroke-width','2.5');path.setAttribute('stroke-linecap','round');path.setAttribute('stroke-linejoin','round');svg.append(path);}};
 paint();if(readOnly){svg.style.pointerEvents='none';return;}
 const point=ev=>{const r=svg.getBoundingClientRect();return[Math.max(0,Math.min(1,(ev.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(ev.clientY-r.top)/r.height))];};
 svg.onpointerdown=ev=>{if(ev.button!==0)return;ev.preventDefault();svg.setPointerCapture(ev.pointerId);current=[point(ev)];};
 svg.onpointermove=ev=>{if(!current||current.length>=10000)return;current.push(point(ev));paint();};
 const finish=()=>{if(current){if(current.length>1&&a.pageDrawing.length<1000)a.pageDrawing.push(current);current=null;changed();paint();}};
 svg.onpointerup=finish;svg.onpointercancel=()=>{current=null;paint();};$('#subject-undo').onclick=()=>{a.pageDrawing.pop();changed();paint();};
}
if(db.exams.length)renderRoute();
